apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: mlflow-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    replicated:
      size: 3
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
parameters:
  objectStoreName: mlflow-store
  objectStoreNamespace: rook-ceph
reclaimPolicy: Retain
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mlflow-artifacts
  namespace: mlops-blue
spec:
  generateBucketName: mlflow-artifacts
  storageClassName: rook-ceph-bucket
